# Generated by Django 6.1.1 on 2026-09-21 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cargo_permisos'),
        ('actividades', '0004_alter_activity_options_alter_activity_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_active',
        ),
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.TextField(blank=True, verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='activity',
            name='item',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ítem'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('REALIZADO', 'Realizado')], default='INGRESADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='accounts.delegacion', verbose_name='Delegación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, verbose_name='Solicitud / problema'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='actividades.contact', verbose_name='Contacto'),
        ),
    ]
