# Generated by Django 6.1.1 on 2026-09-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_contact_remove_activity_is_active_activity_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
