# Generated by Django 6.1.1 on 2026-10-08 21:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_contact_observations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AddField(
            model_name='activity',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Código'),
        ),
    ]
