# Generated by Django 6.1.1 on 2026-10-08 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_alter_contact_options_activity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código'),
        ),
    ]
