# Generated by Django 6.1.1 on 2026-10-08 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_alter_activity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Código'),
        ),
    ]
