# Generated by Django 6.1.1 on 2026-10-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_alter_activity_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('start_date', 'name'), 'permissions': [('manage_activities', 'Puede gestionar actividades'), ('validate_activities', 'Puede validar actividades')], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
