site_name: Sistema de Gestión de Resultados
site_description: Documentación técnica del Sistema de Gestión de Resultados

theme:
  name: material
  language: es

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

  font:
    text: Exo
    code: JetBrains Mono

nav:
  - Inicio:
    - "index.md"


  - Arquitectura:
      - Patrón MTV: arquitectura/mtv.md

  - Autenticación y autorización:
      - "accounts/crear-un-usuario.md"

  - Actividades:
      - Mantenedor de actividades: actividades/mantenedor.md

copyright: Copyright &copy; 2026 Equipo de Desarrollo · Ingeniería Informática · INACAP La Serena
extra:
  generator: false