site_name: Sistema de Gestión de Resultados
site_description: Documentación técnica del Sistema de Gestión de Resultados

theme:
  name: material
  language: es

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

  font:
    text: Exo
    code: JetBrains Mono

nav:
  - Inicio:
    - index.md
    - accounts/iniciar-sesion.md

  - Autenticación y autorización:
      - accounts/iniciar-sesion.md
      - accounts/crear-un-usuario.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - glightbox:
      effect: zoom

copyright: Copyright &copy; 2026 Equipo de Desarrollo · Ingeniería Informática · INACAP La Serena

extra:
  generator: false