# Generated by Django 6.1.1 on 2026-09-14 14:18

from django.db import migrations


def crear_cargos(apps, schema_editor):
    Cargo = apps.get_model("accounts", "Cargo")

    cargos = [
        "Jefe de Delegación",
        "Profesional",
        "Administrativo",
        "Encargado de Área",
        "Técnico",
    ]

    for nombre in cargos:
        Cargo.objects.get_or_create(
            nombre=nombre,
            defaults={"activo": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_cargo_alter_delegacion_options_user_cargo"),
    ]

    operations = [
        migrations.RunPython(crear_cargos),
    ]