# Generated by Django 6.1.1 on 2026-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_first_name_alter_user_last_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='auth.permission', verbose_name='Permisos'),
        ),
    ]
